project_name: scoop-cache-cleaner
builds:
  - env: [ CGO_ENABLED=0 ]
    goos: # 编译平台列表 
      - windows

checksum:
  name_template: 'checksums.txt'

archives:
  - replacements:
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: # 添加到压缩包内的文件列表
      - readme.md
      - readme-zh.md
