name: TestWatch

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      #if: github.actor == github.event.repository.owner.login
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
        cache: true
         
